input {
  beats { port => 5044 }
}

filter {
  if [container][name] == "product-service" {
    json { source => "message" }
    mutate { add_field => { "service" => "product-service" } }
  }
  else if [container][name] == "authentication-service" {
    json { source => "message" }
    mutate { add_field => { "service" => "auth-service" } }
  }
  else if [container][name] == "cart-service" {
    json { source => "message" }
    mutate { add_field => { "service" => "cart-service" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "novera-%{service}-%{+YYYY.MM.dd}"
  }
}
