services.auth=${AUTH_SERVICE_URL}
services.product=${PRODUCT_SERVICE_URL}
services.cart=${CART_SERVICE_URL}
services.order=${ORDER_SERVICE_URL}
services.payment=${PAYMENT_SERVICE_URL}
jwt.secret=${JWT_SECRET}