spring.application.name=payment-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/novera_payment_db
spring.datasource.username=postgres
spring.datasource.password=postgrey@1029

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

##############################
# JWT
##############################

jwt.secret=9aa0cc3502d271ee36315ea50254dfeb7b3e9bf36aa72cd42c661ad4d59ee530
jwt.expiration=86400000

##############################
# Razorpay
##############################

razorpay.key.id=rzp_test_TJIg5B7V5AVWIW
razorpay.key.secret=sM2cjMEK22VL7hhiczWETdGi

##############################
# Order Service
##############################

order.service.url=http://localhost:8083