spring.application.name=payment-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/novera_payment_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

##############################
# JWT
##############################

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

##############################
# Razorpay
##############################

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

##############################
# Order Service
##############################

order.service.url=http://localhost:8083

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true