spring.application.name=authentication-service

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/novera_auth_db
spring.datasource.username=postgres
spring.datasource.password=postgrey@1029

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=9aa0cc3502d271ee36315ea50254dfeb7b3e9bf36aa72cd42c661ad4d59ee530
jwt.expiration=86400000

# ===============================
# Swagger
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html