spring.application.name=order-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/novera_orders
spring.datasource.username=postgres
spring.datasource.password=postgrey@1029

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=9aa0cc3502d271ee36315ea50254dfeb7b3e9bf36aa72cd42c661ad4d59ee530
jwt.expiration=86400000

auth.service.url=http://localhost:8080
product.service.url=http://localhost:8081
cart.service.url=http://localhost:8082