spring.datasource.url=${ORDER_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
auth.service.url=${AUTH_SERVICE_URL}
product.service.url=${PRODUCT_SERVICE_URL}
cart.service.url=${CART_SERVICE_URL}
jwt.secret=${JWT_SECRET}
