spring.datasource.url=jdbc:postgresql://postgres-db:5432/novera_orders

auth.service.url=http://authentication-service:8080
product.service.url=http://product-service:8081
cart.service.url=http://cart-service:8082
