# spring.datasource.url=jdbc:postgresql://postgres-db:5432/novera_cart_db
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/novera_cart_db
product.service.url=http://product-service:8081
