apiVersion: v1
kind: ConfigMap
metadata:
  name: novera-config
  namespace: novera
data:
  # ===============================
  # PostgreSQL
  # ===============================
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres

  # ===============================
  # Database URLs (K8s internal DNS)
  # ===============================
  AUTH_DB_URL: jdbc:postgresql://postgres-db:5432/novera_auth_db
  CART_DB_URL: jdbc:postgresql://postgres-db:5432/novera_cart_db
  ORDER_DB_URL: jdbc:postgresql://postgres-db:5432/novera_orders
  PAYMENT_DB_URL: jdbc:postgresql://postgres-db:5432/novera_payment_db
  PRODUCT_DB_URL: jdbc:postgresql://postgres-db:5432/productdb

  # ===============================
  # Service-to-Service URLs (K8s internal DNS)
  # ===============================
  AUTH_SERVICE_URL: http://authentication-service:8080
  PRODUCT_SERVICE_URL: http://product-service:8081
  CART_SERVICE_URL: http://cart-service:8082
  ORDER_SERVICE_URL: http://order-service:8083
  PAYMENT_SERVICE_URL: http://payment-service:8084
  GATEWAY_SERVICE_URL: http://gateway-service:8085

  # ===============================
  # JPA / Hibernate
  # ===============================
  JPA_DDL_AUTO: update
  JPA_SHOW_SQL: "true"

  # ===============================
  # JWT (non-sensitive part)
  # ===============================
  JWT_EXPIRATION: "86400000"
