name: Novera CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Authentication Service
        working-directory: ./authentication-service
        run: mvn clean package -DskipTests

      - name: Build Product Service
        working-directory: ./product-service
        run: mvn clean package -DskipTests

      - name: Build Cart Service
        working-directory: ./cart-service
        run: mvn clean package -DskipTests

      - name: Build Order Service
        working-directory: ./order-service
        run: mvn clean package -DskipTests

      - name: Build Payment Service
        working-directory: ./paymnet-service
        run: mvn clean package -DskipTests

      - name: Build Gateway Service
        working-directory: ./gateway-service
        run: mvn clean package -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/novera-frontend/package-lock.json

      - name: Build Frontend
        working-directory: ./frontend/novera-frontend
        env:
          VITE_PRODUCT_API: http://localhost
          VITE_AUTH_API: http://localhost
          VITE_CART_API: http://localhost
          VITE_ORDER_API: http://localhost
          VITE_PAYMENT_API: http://localhost
        run: |
          npm ci
          npm run build

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/novera-frontend:0.2.1 \
            ./frontend/novera-frontend

      - name: Push Frontend image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/novera-frontend:0.2.1

      - name: Build Product Service image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/novera-product-service:0.2.5 \
            ./product-service
 
      - name: Push Product Service image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/novera-product-service:0.2.5

      - name: Build Authentication Service image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/novera-auth-service:0.2.5 \
            ./authentication-service

      - name: Push Authentication Service image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/novera-auth-service:0.2.5

      - name: Build Cart Service image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/novera-cart-service:0.2.5 \
            ./cart-service

      - name: Push Cart Service image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/novera-cart-service:0.2.5

      - name: Build Order Service image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/novera-order-service:0.2.5 \
            ./order-service

      - name: Push Order Service image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/novera-order-service:0.2.5

      - name: Build Payment Service image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/novera-payment-service:0.2.5 \
            ./paymnet-service

      - name: Push Payment Service image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/novera-payment-service:0.2.5

      - name: Build Gateway Service image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/novera-gateway-service:0.2.5 \
            ./gateway-service

      - name: Push Gateway Service image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/novera-gateway-service:0.2.5